source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.10"
gem "jekyll-seo-tag", "~> 2.8"

# Required by Ruby 3.4+ (no longer bundled with the standard library)
gem "webrick", "~> 1.9"
gem "csv", "~> 3.3"
gem "base64", "~> 0.2"
